export const LOGIN_OK = "LOGIN_OK"
export const LOGING = "LOGING"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const START_GET_ACCESS_TOKEN = "START_GET_ACCESS_TOKEN"
export const GET_ACCESS_TOKEN_SUCCESS = "GET_ACCESS_TOKEN_SUCCESS"
export const FAIL_GET_ACCESS_TOKEN = "FAIL_GET_ACCESS_TOKEN"

export const START_REGISTER = "START_REGISTER"
export const REGISTER_OK = "REGISTER_OK"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const PASSWORD_CHANGING = "CHANGING_PASSWORD"
export const PASSWORD_CHANGE_SUCCESS = "CHANGE_SUCCESS_PASSWORD"
export const PASSWORD_CHANGE_FAIL = "CHANGE_FAIL_PASSWORD"