export const LOGIN_OK = "LOGIN_OK"
export const LOGING = "LOGING"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const START_GET_ACCESS_TOKEN = "START_GET_ACCESS_TOKEN"
export const GET_ACCESS_TOKEN_SUCCESS = "GET_ACCESS_TOKEN_SUCCESS"
export const FAIL_GET_ACCESS_TOKEN = "FAIL_GET_ACCESS_TOKEN"