export const LOGIN_OK = "LOGIN_OK"
export const LOGING = "LOGING"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const START_GET_ACCESS_TOKEN = "START_GET_ACCESS_TOKEN"
export const GET_ACCESS_TOKEN_SUCCESS = "GET_ACCESS_TOKEN_SUCCESS"
export const FAIL_GET_ACCESS_TOKEN = "FAIL_GET_ACCESS_TOKEN"

export const START_REGISTER = "START_REGISTER"
export const REGISTER_OK = "REGISTER_OK"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const PASSWORD_CHANGING = "CHANGING_PASSWORD"
export const PASSWORD_CHANGE_SUCCESS = "CHANGE_SUCCESS_PASSWORD"
export const PASSWORD_CHANGE_FAIL = "CHANGE_FAIL_PASSWORD"

export const INFO_LOADING = 'INFO_LOADING'
export const INFO_LOAD_SUCCESS = 'INFO_LOAD_SUCCESS'
export const INFO_LOAD_FAIL = 'INFO_LOAD_FAIL'

export const UPDATING_INFO = "INFO_UPDATING"
export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS"
export const UPDATE_INFO_FAIL = "UPDATE_INFO_FAIL"

export const UPLOADING_AVATAR = "UPLOADING_AVATAR"
export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS"
export const UPLOAD_AVATAR_FAIL = "UPLOAD_AVA_FAIL"