export default {
    WARRING : "WARRING",
    NULL_IN_USER_PASS_REPASS: 'Vui lòng nhập đủ các trường',
    MIN_LENGTH_OF_PASS: 'Mật khẩu phải có tối thiểu 6 ký tự',
    INVALID_PASSWORD : "Re password is not same your password!",
    SIGN_UP: "ĐĂNG KÝ",
    SIGN_OUT: 'Đăng xuất',
    LOG_IN: 'ĐĂNG NHẬP',
    UPDATE: "CẬP NHẬT",
    DESCRIPTION_TEXT_INPUT_OTP:"Nhập mã xác thực được gửi về số ĐT của bạn",
    UPDATE_YOUR_PHONE_NUMBER:'Cập nhật số điện thoại của bạn',
    OTP_VI: "Mã xác thực",
    PHONE_NUMBER_VI: "Số điện thoại",
    PASSWORD_VI: "Mật khẩu",
    RE_PASSWORD_VI:"Nhập lại mật khẩu",
    FORGOT_PASSWORD: 'Quên mật khẩu?',
    OR_LOGIN_BY:'Hoặc đăng nhập bằng',
    FACEBOOK: "FACEBOOK",
    TELEPHONENUMBER: 'telephoneNumber',
    NUMRIC:'numeric',
    TRANSPARENT: 'transparent',
    USER_NAME_VI: "Tên đăng nhập",
    NEXT_GAME: 'Game tiếp theo',
    JOIN: "Tham gia",
    SYSTEM_ROOM: 'Phòng hệ thống',
    FRIEND_ROOM:"Phòng bạn bè",
    TRAINING_ROOM: "Phòng tập luyện",
    LIST_FRIEND: 'Danh sách bạn bè',
    ONLINE: 'online',
    INVITE: 'Mời bạn',
    YES_BTN: "ĐỒNG Ý",
    CREATE_ROOM:'TẠO PHÒNG',
    ROOM_NAME: 'Tên phòng',
    ROOM_PASSWORD:'Mật khẩu phòng',
    SCORE_ACCUMULATION: 'Điểm tích lũy',
    STOP_PLAY_GAME: 'Dừng cuộc chơi',
    YOUR_ANSWER_WRONG: "Bạn đã trả lời sai",
    GAME_OVER:'VÒNG CHƠI KẾT THÚC',
    CONFIRM: 'XÁC NHẬN',
    START: 'BẮT ĐẦU',
    QUANTITY_MEMBER_JOIN: 'Số người tham gia',
    TALK: 'Nói chuyện',
    SEND:'send',
    FAIL : 'FAIL!',
    INTERNET_NOT_CONNECTED: "Bạn không có kết nối internet, vui lòng kết nối để thử lại",
    NEWS_VI : "Tin tức",
    CHANGE_PASSWORD: 'Đổi mật khẩu',

    GIFT_HISTORY: 'Lịch sử đổi quà',
    GAME_HISTORY:'Lịch sử chơi',
    TIME_CHANGE_GIFT: 'Thời gian đổi',
    TIME_PLAY_GAME: 'Thời gian chơi',
    RIGHT_ANSWER_GAME: 'Trả lời đúng',
    SCORE_CHANGE_GIFT: 'Số điểm đổi',
    GIFT_CHANGED: 'Quà đã đổi',
    BIRTH_DAY: 'Ngày sinh',
    GAME: 'Game',
    RANK: 'Rank',
    PROFILE: 'Profile',
    GENDER: 'Giới tính',
    DISPLAY_NAME: 'Tên hiển thị',

    OLD_PASSWORD: 'Mật khẩu cũ',
    NEW_PASSWORD: 'Mật khẩu mới',
    RE_NEW_PASSWORD: 'Nhập lại mật khẩu mới',

    DISPLAY_NAME: 'Tên hiển thị',
    UPDATE_AVATAR: 'Cập nhật Avatar',
    ADDRESS: 'Địa chỉ',

    CENTER: 'center',
    STRETCH: 'stretch',
    COVER: 'cover',
    NOTIFICATION: 'Thông Báo',
    MISSING_DATA: "Dữ liệu gửi thiếu",

    
}